### ISSUE TITLE
Bug encontrado

### ISSUE THREAD

**Issue by Allisson98** [matheus20111997/SistemaJoin#1]
![sem titulo](https://user-images.githubusercontent.com/23202062/44526236-c3446480-a6b9-11e8-8861-243ac1a623a1.jpg)
Tela Home do Administrador.

**Comment by cabalbarreto** [comment]
Não estou vendo a descrição do problema. Logo não entendo o porque da tela, ainda não entendeu o que tem para fazer?

**Comment by Allisson98** [comment]
Eu estava apenas "conhecendo" essa funcionalidade do GitHub. Na verdade ainda estou, portando desconsiderem esse meu equivoco, e já tentei excluí mais não consegui. Para ser sincero ainda não sei se exclui, então se alguém souber, agradeço se puder me ensinar.

**Comment by cabalbarreto** [comment]
Entendo. Mas veja, entendo por "estar conhecendo" a resposta a pergunta: O que acontece se fizer isso ou aquilo, certo? Já quanto a descrição dos fatos é diferente, então minha questão foi tentar entender se não colocou porque não sabia o que colocar ou se não colocou por não saber onde colocar. Entendeu?

**Comment by matheuspereiradev** [comment]
Essas views estão bagunçadas pois ainda estou realizando algumas ligações nessa tela, já que nela serão efetuadas mudanças solicitadas por Renata e se faz necessário retirar as ligações, mas já está sendo trabalhada essa tela.
