### ISSUE TITLE
Escola

### ISSUE THREAD

**Issue by Allisson98** [matheus20111997/SistemaJoin#11]
Quando vai cadastrar uma escola e deixa um campo em branco, o sistema para.

**Comment by Allisson98** [comment]
Está cadastrado a escola com o telefone incompleto.

**Comment by Allisson98** [comment]
Quando ta exibindo as informações de uma escola e aperto em voltar, o sistema está indo para a home. O correto é para voltar para a lista.

**Comment by Allisson98** [comment]
Se clico em editar escola e não quero mais editar, e aperto em voltar, o sistema está indo para a home. O correto é: voltar para a lista.

**Comment by PRMFeitosa** [comment]
revisado...
