### ISSUE TITLE
Professor

### ISSUE THREAD

**Issue by Allisson98** [matheus20111997/SistemaJoin#14]
Na lista as informações estão com uma ordem, quando vai para editar os campos mudam de posição. EX.: Telefone, Email eles se invertem.

**Comment by Allisson98** [comment]
Quando ta exibindo as informações de um profesor e aperto em voltar, o sistema está indo para a home. O correto é para voltar para a lista.

**Comment by Allisson98** [comment]
Se clico em editar professor e não quero mais editar, e aperto em voltar, o sistema está indo para a home. O correto é: voltar para a lista.

**Comment by Allisson98** [comment]
Está cadastrando com o telefone incompleto. Ex.: (88) 9 9878-99

**Comment by matheuspereiradev** [comment]
no caso seria se você estivesse dentro do editor e decidisse descartar as informações inseridas é isso?

**Comment by matheuspereiradev** [comment]
manda print desse da lista

**Comment by Allisson98** [comment]
Assim: Você está visualizando as informações de um professor, aí está nessa ordem os campos: Nome, Email, Telefone, CPF. Então desejo alterar algum dado do professor, ao clicar no botão de editar a ordem dos campos ficam: Nome, Telefone, Email, CPF.
Então é para deixar a mesma ordem.

**Comment by PRMFeitosa** [comment]
parte Java esta resolvido
