### ISSUE TITLE
Escola

### ISSUE THREAD

**Issue by Allisson98** [matheus20111997/SistemaJoin#19]
Não está cadastrando escola.

**Comment by Allisson98** [comment]
Ajeitar a mensagem de toast quando vai excluir a escola, para: Deseja realmente excluir a escola?

**Comment by Allisson98** [comment]
Não está editando as informações da escola.

**Comment by Allisson98** [comment]
Quando clica em uma escola para visualizar as informações da mesma, quando voltar é para voltar para a lista de escolas cadastradas, ta voltando é para a tela home.

**Comment by Allisson98** [comment]
Retirar o status no listar escola.

**Comment by GitTec** [comment]
Criar um espaço para setar as informações de contato da escola

**Comment by GitTec** [comment]
Criar um espaço para adicionar as informações de contato da escola.

**Comment by GitTec** [comment]
Mudar a frase de dados inválidos do email da escola. EX: Cadastrei o email da escola errado, e a mensagem está diferente: Colocar a mensagem: Os dados inseridos são inválidos.

**Comment by GitTec** [comment]
Editei o email da escola sem o @ e passou.

**Comment by GitTec** [comment]
Editei uma escola no campo nome apenas com espaços e passou.

**Comment by GitTec** [comment]
Editei o campo nome da escola apenas com números e passou.

**Comment by PRMFeitosa** [comment]
finalizado
