### ISSUE TITLE
Turma

### ISSUE THREAD

**Issue by Allisson98** [matheus20111997/SistemaJoin#20]
Quando estou nas informações da turma e volto, é para voltar para a lista de turmas.

**Comment by Allisson98** [comment]
Quando vai editar a turma não está setando os dados que já existem.

**Comment by GitTec** [comment]
Quando vou cadastrar um professor ou aluno em uma turma, deve retornar a mensagem: Deseja inserir o aluno<Nome do aluno>à turma<Nome da turma>?
O mesmo serve para o professor.

**Comment by GitTec** [comment]
Fui cadastrar uma turma, cadastrei os campos nome/turno da turma e inseri apenas um dos valores da faixa etária e cliquei em salvar, o sistema parou.
