### ISSUE TITLE
Cadastrar aluno

### ISSUE THREAD

**Issue by Allisson98** [matheus20111997/SistemaJoin#22]
Está salvando o aluno sem o email do responsável.
Na tela de cadastro o campo está Telefone do responsável, já na lista está só Telefone.
Está trocado a ordem telefone e email na lista.

**Comment by matheuspereiradev** [comment]
Está trocado a ordem telefone e email na lista--> qual lista?

**Comment by matheuspereiradev** [comment]
Na tela de cadastro o campo está Telefone do responsável, já na lista está só Telefone---> é pra não ficar muito grande e atrapalhar com o tamanho e no cadastro é pra auxiliar somente

**Comment by Allisson98** [comment]
Na tela com as informações do aluno.
Sim, mais os outros campos todos tem Nome do responsável, CPF do responsável, e-mail do responsável, só o telefone que não.
