### ISSUE TITLE
Cadastrar Professor

### ISSUE THREAD

**Issue by Allisson98** [matheus20111997/SistemaJoin#4]
Está cadastrando o professor sem o nome;
Ao clicar no botão:"Listar Professores", mostra a lista dos professores cadastrados mais em à cima da lista aparece o nome:Listar escolas cadastradas.
Está cadastrando o professor sem data de nascimento.

**Comment by PRMFeitosa** [comment]
não e para cadastrar data de nascimento mesmo não se tiver o campo Matheus vai retirar, @matheus20111997  esse textview acima da lista professores confere ai.
